language: python

python:
  - 2.7

before_install:
 - sudo apt-get update -qq

install:
 - sudo apt-get install -qq libnetcdf-dev gfortran
 - git clone git://github.com/derpycode/ctoaster.cupcake-data.git $TRAVIS_BUILD_DIR/../ctoaster.cupcake-data
 - git clone git://github.com/derpycode/ctoaster.cupcake-test.git $TRAVIS_BUILD_DIR/../ctoaster.cupcake-test
 - cd $TRAVIS_BUILD_DIR
 - ./tools/travis-setup

script:
 - ./tests run basic
